### ISSUE TITLE
IE11 Support

### ISSUE THREAD

**Issue by zurie** [homerjam/scrollwizardry#2]
By using 
`arr.includes(searchElement)
arr.includes(searchElement, fromIndex)`
 you exclude the ability for people on IE11 to use ScrollWizardry

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

Do you have any thoughts on dropping includes for something else or supporting IE10/11 with a polyfill, possibly optional? Or do you think that if the user needs IE10/11 support they should supplement with their own polyfill from the above link?

**Comment by homerjam** [comment]
Does it work with `indexOf`?

**Comment by zurie** [comment]
I don’t know. I assume so because that’s what was recommended as an alternative but using the poly fill on the site allows it to work as is. But it’s a little bit more bloat. So it’s either baked in, added as a poly fill, or left out with the intention that for ie11 support people are on their own.
