### ISSUE TITLE
triggerElement doesn't work in example?

### ISSUE THREAD

**Issue by artyor** [homerjam/scrollwizardry#7]
Hey, when I changed triggerElement to otehr ID or Class, it doesn't change anything, it doesn't change place of indicators either? I'm talking about index.html in example folder. 

It's been a while since anyone asked here anything, hope you still answer :)

**Comment by homerjam** [comment]
Hey can you post an example so I can see what you mean?

**Comment by artyor** [comment]
> Hey can you post an example so I can see what you mean?

https://github.com/artyor/artyor/tree/master/ArtyScrollWizardy

Here I made a fast example based on your example. Whatever I set for triggerElement, it wont change, indicator 'start' stays in same place.

**Comment by homerjam** [comment]
The start/end indicators are relative to the viewport - you might want to check out the scrollmagic docs to get a better understanding of how it works

**Comment by artyor** [comment]
The end indicator is relative to the duration, but start indicator is relative to triggerElement.
Here is ScrollMagic official demo: https://scrollmagic.io/examples/basic/simple_tweening.html

**Comment by homerjam** [comment]
Oh yeah, sorry it's the trigger that's relative to the viewport.

I'd need to see a live example if possible

**Comment by artyor** [comment]
Hey no problem, I was confused myself. 
Sorry, I can't setup webpack now, I'm on my secundary laptop, and I there is no CDN for scrollwizardry.
Could you download/clone my github example I made? Otherwise I could try to remake it with some online editor...

**Comment by homerjam** [comment]
No time at the minute but you should be able to get scrollwizardry via unpkg

**Comment by artyor** [comment]
https://codepen.io/artyor/pen/Baadzoy 
Here it is, thanks in advance for your time :)

As you can tell, I set triggerElement to my fifth div, yet it starts at the top, exactly where triggerHook starts aswell.

**Comment by artyor** [comment]
Hey homerjam, did you have time too look into codepen?
